apiVersion: v1
kind: Secret
metadata:
  name: promotions-db
  namespace: default
type: Opaque
stringData:
  # Must match the ClusterIP Service name from K8S-08 (host=postgres)
  # Username/password/database name must match the env config in the K8S-07 StatefulSet
  DATABASE_URI: postgresql+psycopg://postgres:postgres@postgres:5432/promotions
