apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432           # Service port exposed within the cluster
      targetPort: postgres # Maps to the named port inside the Pod (named "postgres" in the StatefulSet)
      protocol: TCP
